import os
import random

# Define the directory to store files
directory = "sample_data"
os.makedirs(directory, exist_ok=True)

# List of topics and detailed content
topics = {
    "AI": "Artificial Intelligence (AI) is transforming industries by automating tasks, enhancing decision-making, and enabling new business models. AI encompasses machine learning, natural language processing, and deep learning, which help computers perform tasks that typically require human intelligence. AI is widely used in healthcare, finance, marketing, and autonomous systems. The growth of AI has led to innovations such as chatbots, recommendation engines, and self-driving cars. While AI promises efficiency and improved productivity, it also raises concerns regarding ethics, job displacement, and biases in machine learning models. Companies worldwide are investing in AI to drive competitive advantages, improve user experiences, and optimize processes. As AI continues to evolve, responsible AI development and ethical considerations will remain crucial for sustainable progress.",
    "Cloud Computing": "Cloud computing provides on-demand access to computing resources and services over the internet. It enables businesses to scale applications, store large amounts of data, and deploy services without needing to maintain physical infrastructure. Cloud platforms like AWS, Azure, and Google Cloud offer various services, including infrastructure-as-a-service (IaaS), platform-as-a-service (PaaS), and software-as-a-service (SaaS). Organizations benefit from reduced costs, increased flexibility, and enhanced collaboration through cloud-based solutions. Security and data privacy remain key concerns in cloud computing, leading to innovations in encryption, access control, and compliance measures. As more enterprises embrace multi-cloud and hybrid-cloud strategies, the future of cloud computing will focus on interoperability, sustainability, and AI-driven automation.",
    "Cybersecurity": "Cybersecurity is essential for protecting digital assets, sensitive data, and systems from cyber threats such as hacking, phishing, and ransomware attacks. Organizations implement cybersecurity measures like firewalls, encryption, and multi-factor authentication to safeguard networks and prevent unauthorized access. With the rise of cloud computing, IoT, and remote work, the attack surface for cyber threats has expanded significantly. Governments and enterprises invest heavily in cybersecurity training, threat intelligence, and incident response planning to mitigate risks. Zero Trust Architecture, AI-driven threat detection, and blockchain-based security solutions are shaping the future of cybersecurity. As cyber threats continue to evolve, the demand for skilled cybersecurity professionals and advanced security technologies will increase.",
    "Blockchain": "Blockchain technology ensures secure, transparent, and tamper-proof transactions in digital ecosystems. It operates on a decentralized ledger, making it highly resistant to fraud and data manipulation. Initially popularized by cryptocurrencies like Bitcoin, blockchain has since found applications in supply chain management, identity verification, and smart contracts. Industries such as finance, healthcare, and logistics are leveraging blockchain for enhanced security, reduced transaction costs, and improved traceability. Despite its potential, blockchain faces challenges like scalability, regulatory concerns, and energy consumption in mining operations. Future advancements in blockchain, including Layer 2 scaling solutions and interoperability protocols, will drive wider adoption across sectors.",
    "Quantum Computing": "Quantum computing leverages quantum mechanics to process information at speeds far beyond classical computers. Unlike traditional bits, quantum bits (qubits) can exist in multiple states simultaneously, enabling parallel processing and solving complex problems efficiently. Quantum computing has the potential to revolutionize fields such as cryptography, materials science, and drug discovery. Companies like IBM, Google, and startups are racing to develop practical quantum computers with stable qubits and error correction mechanisms. While quantum computing is still in its early stages, its impact on encryption and data security is a major area of concern. Governments and enterprises are investing in quantum-safe cryptographic solutions to prepare for a future where quantum computers could break current encryption standards.",
    "Space Exploration": "Space exploration aims to expand our knowledge about the universe through advanced technology and research. Agencies like NASA, ESA, and private companies such as SpaceX and Blue Origin are developing next-generation spacecraft, lunar bases, and Mars missions. Innovations in satellite technology, AI-driven navigation, and reusable rocket systems are making space exploration more cost-effective and sustainable. The search for extraterrestrial life, asteroid mining, and interstellar travel remain key areas of interest. Space-based technologies contribute to Earth’s economy through satellite communication, climate monitoring, and GPS navigation. As nations and private entities collaborate on space missions, ethical and governance challenges related to space resources and colonization will become more prominent.",
    "Renewable Energy": "Renewable energy sources like solar, wind, and hydropower are crucial for reducing carbon emissions and mitigating climate change. Advances in battery storage, grid integration, and energy efficiency are driving the transition to a sustainable energy future. Governments worldwide are investing in policies that support renewable energy adoption, aiming to replace fossil fuels with clean alternatives. Solar panels, offshore wind farms, and hydrogen fuel cells are becoming more cost-competitive due to technological advancements and economies of scale. Despite progress, challenges such as energy intermittency, land use conflicts, and infrastructure upgrades remain. The future of renewable energy lies in smart grids, decentralized energy systems, and innovations in energy storage technologies.",
    "Biotechnology": "Biotechnology innovations are revolutionizing medicine, agriculture, and environmental conservation. Breakthroughs in genetic engineering, CRISPR gene editing, and synthetic biology enable scientists to develop new treatments, increase crop yields, and produce biofuels. Biotechnology plays a key role in developing personalized medicine, targeting specific genetic conditions for improved patient outcomes. The field also contributes to sustainable agriculture through genetically modified organisms (GMOs) that resist pests and tolerate extreme climates. Ethical considerations, regulatory challenges, and public perceptions of biotechnology influence its adoption. As biotech continues to advance, collaborations between researchers, policymakers, and industry leaders will be essential to maximize its benefits while addressing potential risks."
}

# Create 1000 files
for i in range(1, 10001):
    topic = random.choice(list(topics.keys()))
    content = f"Topic: {topic}\n\n{topics[topic]}"
    file_name = os.path.join(directory, f"file_{i}.txt")
    
    with open(file_name, "w") as f:
        f.write(content)

print(f"10000 files created in '{directory}' directory.")
